### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Aixebar** [yiyuanliu/FlipGank#1]
app闪退  环境：魅族MX5(Android 5.1,API 22)

**Comment by Lesences** [comment]
小米5同样闪退

**Comment by yiyuanliu** [comment]
感谢反馈，等考完试我看下。

**Comment by yiyuanliu** [comment]
已修复，感谢反馈，请在 [release page](https://github.com/yiyuanliu/FlipGank/releases) 下载新 apk。
